### PR TITLE
bump version + scale changed to INT

### PR DESCRIPTION
**Pull request by seitenca**

### CODE REVIEW

**Comment by Pilad** [comment]
Does not apply the new value, it is reset back to 5. When in the game you move the slider by 10 for example.
# The overlay will be scaled by this amount.
    S:scale=5

**Comment by seitenca** [comment]
> Does not apply the new value, it is reset back to 5. When in the game you move the slider by 10 for example.
> 
> # The overlay will be scaled by this amount.
> ```
> S:scale=5
> ```
Try to reset the config or change S:scale=5 to I:scale=5

**Comment by seitenca** [comment]
@Pilad true, Idk why the compiled version of @Dream-Master not work.
Please try my compiled version https://github.com/seitenca/InGame-Info-XML/releases/tag/2.8.1.84

**Comment by seitenca** [comment]
@Pilad It works for me, please tell me if the change works for you

**Comment by Pilad** [comment]
I deleted the file(InGameInfoXML.cfg) and this fixed the problem.

**Comment by Pilad** [comment]
S:scale=1.0 old 
I:scale=10 new

**Comment by Pilad** [comment]
What is the point of fixing the code? Removed the comma. It was 1.0, after which it became just a whole 10.

**Comment by seitenca** [comment]
Because better number display reasons, I patched it already https://github.com/GTNewHorizons/NewHorizons/commit/e32e058e9a417576b8f5f070d535bad37a882f8c so dont worry

**Comment by seitenca** [comment]
@Pilad look at this https://cdn.discordapp.com/attachments/683624875847581708/686188935927431255/unknown.png

**Comment by Pilad** [comment]
Ok )))

**Pull request merged**
